name: Docs

on:
  push:
    paths:
      - 'doc/*'
    branches:
      - '4.0'
  pull_request:
    paths:
      - 'doc/*'
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
        working-directory: 'doc'
      - run: npm run build
        working-directory: 'doc'
      - run: npm run lint
        working-directory: 'doc'
      - run: npm run lint:links
        working-directory: 'doc'
